#!/bin/bash
#
#                         _     _
#                   _ __ | |__ | | __     _ __ ___   __ _  ___
#                  | '_ \| '_ \| |/ /____| '_ ` _ \ / _` |/ __|
#                  | | | | | | |   <_____| | | | | | (_| | (__
#                  |_| |_|_| |_|_|\_\    |_| |_| |_|\__,_|\___|
#
#                              Welcome to nhk-mac.
#
#          nhk-mac is a CLI for quickly setting up a new workstation.

source src/run
